version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "55432:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres
  sharp_backend:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      - postgres
volumes:
  progresDB:
networks:
  postgres:
    driver: bridge
    expose: true